using CairoMakie

"""
plot_mcmc_densities!(chain_X; n_columns=3)

Plots marginal density distributions for each parameter in the 
constituent parameter vectors of `chain_X`, each representing a sample
generated by MCMC.
"""
function plot_mcmc_densities!(chain_X, parameter_names; 
                                n_columns = 3,
                                directory = pwd(),
                                filename = "mcmc_densities.png")

    fig = Figure(resolution = (500n_columns, 200n_rows))

    N_param = length(first(chain_X))
    n_rows = Int(ceil(N_param / n_columns))
    ax_coords = [(i, j) for i = 1:n_rows, j = 1:n_columns]
    
    for (i, param_name) in enumerate(parameter_names)
        samples = getindex.(chain_X, i)

        coords = ax_coords[i]
        ax = Axis(fig[coords...],
            xlabel = param_name,
            ylabel = "Density")
        ax.xlabelsize = 20
    
        density!(ax, samples)
    end

    save(joinpath(directory, filename), fig)
end
